matchBlocks=mud sand cobblestone dirt gray_concrete dripstone_block tuff calcite dirt_path hay_block gravel clay coarse_dirt bricks cracked_stone_bricks stone quartz_block oak_planks spruce_planks birch_planks jungle_planks acacia_planks dark_oak_planks stone_bricks mossy_cobblestone white_terracotta orange_terracotta magenta_terracotta light_blue_terracotta yellow_terracotta lime_terracotta pink_terracotta gray_terracotta light_gray_terracotta cyan_terracotta purple_terracotta blue_terracotta brown_terracotta green_terracotta red_terracotta black_terracotta terracotta andesite diorite granite
method=overlay
tiles=0-16
connect=block
connectBlocks=packed_mud
layer=cutout
weights=50