matchBlocks=andesite clay coal_ore cobblestone cracked_stone_bricks diamond_ore emerald_ore gold_ore grass_block dirt_path gravel terracotta iron_ore lapis_ore mossy_cobblestone netherrack oak_planks spruce_planks birch_planks jungle_planks acacia_planks dark_oak_planks podzol quartz_block redstone_ore light_gray_glazed_terracotta white_terracotta orange_terracotta magenta_terracotta light_blue_terracotta yellow_terracotta lime_terracotta pink_terracotta gray_terracotta light_gray_terracotta cyan_terracotta purple_terracotta blue_terracotta brown_terracotta green_terracotta red_terracotta black_terracotta stone stone_bricks
method=overlay
tiles=0-16
connectBlocks=hay_block
layer=cutout
