skins.2=2
biomes.2=frozen_ocean frozen_ocean cold_ocean cold_ocean frozen_river snowy_beach snowy_taiga snowy_taiga snowy_taiga snowy_plains snowy_slopes ice_spikes

skins.3=2
name.3=iregex:(iceologer|chillager)